# Конфигурация для трансформации Excel файлов
output_filename: репорт.xlsx
mappings:
    - source: Worksheet!A1:H100000
      destination: Результат Лист1!A1
      filter_column: A
      filter_mask: ПСА*
output_sheets:
    - name: Результат Лист1
      create_if_not_exists: true
